apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: prod
  labels:
    django-app: django
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    django-app: django

