apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: prod
  labels:
    django-app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      django-app: django
  template:
    metadata:
      name: django
      labels:
        django-app: django
    spec:
      containers:
      - name: django
        image: asia.gcr.io/gcp-akash-287109/django-test@sha256:241df1d61f53b3d85077edce83ac9046424c8ec537f202e0150950cda20f0014
      imagePullSecrets:
      - name: registrypullsecret
